application:
  port: 8000
  host: 0.0.0.0

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false

email_client:
  base_url: "127.0.0.1"
  sender_email: "test@ryuma017.com"
  authorization_token: "postmark-secret-token"
  timeout_milliseconds: 10000
